#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum Precedence {
    None = 0,
    Assign = 1,
    Range = 2,
    ShortOr = 3,
    ShortAnd = 4,
    Equal = 5,
    Inequal = 6,
    EagerOr = 7,
    EagerXor = 8,
    EagerAnd = 9,
    Shift = 10,
    Addive = 11,
    Mulive = 12,
    Cast = 13,
    Unary = 14,
    Bind = 15,
    Pair = 16,
    Prop = 17,
}
